### ISSUE TITLE
onTap or onPress for Polygon?

### ISSUE THREAD

**Issue by jasonflaherty** [jozes/flutter_map_geojson#1]
Just checking out your library here! Cool stuff. I don't see onTap/press for Polygons. Am I missing it? Thanks!

**Comment by jozes** [comment]
Hi @jasonflaherty!

You are right, there is no onTap functionality for polygons. The reason is that this functionality should be implemented as method of Polygon class in flutter_map package. 
Of course one can implement this functionality as kind of extension to Polygon class. The main problem I see here is that we should not duplicate the polygon data - the outer and potential inner rings (holes) consisting of points. IMHO each Polygon should have implemented a property called MBR (Minimum Bounding Rectangle) which is calculated from the points in outer and inner rings. When the user clicks on the map then we can check with 4 "if" comparisons if the clicked point is inside the polygon's MBR and if that is true then the actual point-in-polygon test can be conducted to determine if the point is really inside the polygon. Such implementation would dramatically shorten the amount of time to traverse the list of polygons. Even better would be to build a spatial index on top of polygons or MBRs which could then be quickly accessed and candidate polygons found. 
If we would duplicate all data and not use some advanced method to eliminate false candidates quickly the onTap method could take a lot of processing, especially when there are thousands of polygons to be searched through. 

The main purpose of this package is parsing the GeoJson  and creating map objects. Unfortunately the Polygon class has no onTap method so I hope that this will be implemented in future. Currently I have no plans to implement this functionality.

If you are willing

**Comment by beeekey** [comment]
Is there any hack for this problem? I need the same.
