### ISSUE TITLE
geojson to latlng

### ISSUE THREAD

**Issue by Hamxa117411** [jozes/flutter_map_geojson#15]
in geojson corrdination value 
  [
                           [
                              212.1079454740286,
                              56.97082786802997
                           ],
                           [
                              224.46248916782633,
                              64.50936114954698
                           ],
                           [
                              245.94986061613014,
                              75.8975769875282
                           ],
                           [
                              13.041330817213094,
                              77.07190622818226
                           ],
                           [
                              212.1079454740286,
                              56.97082786802997
                           ]
                        ]
when it convert to latlng its give an error because latlng range is
Latitude is specified in degrees within the range [-90, 90]. Longitude is specified in degrees within the range [-180, 180).
how we can handle this json

**Comment by jozes** [comment]
I don't see any possible solution to solve this problem in this package because the the LatLng coordinates are specified as you stated. I even don't know how to make these coordinates valid. If these are geographical coordinates in WGS84 projection then they can't be displayed in any software. There are online GeoJson viewers available on internet.  If these coordinates are stored in some "special" or "local" coordinate system then they should be transformed to WGS84 system before they can be displayed.
