### ISSUE TITLE
parsing of non-double coordinates

### ISSUE THREAD

**Issue by nucleus-ffm** [jozes/flutter_map_geojson#20]
Thank you for your work. It is really helpful, but I have some geojson data which sometimes contains coordinates like `[10,47.7875]`. The first value is not a double value; therefore, the casting e.g here: https://github.com/jozes/flutter_map_geojson/blob/836d61835d9e178362c256f085ba028d0fb6235e/lib/src/geojson_parser.dart#L279 results in the exception: 

`type 'int' is not a subtype of type 'double' in type cast`

**Expected behavior:**
Correct parsing of non-double coordinates.

**Comment by jozes** [comment]
As per RFC 7946 for geojson  (see https://datatracker.ietf.org/doc/html/rfc7946#page-11) the point (position) is specified with decimal numbers.

 <quote>A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element.</quoute>

Of course it is possible to change the code and test for the type of numbers parsed: either they are decimal or integers. But this would significantly slow down the parser and that is not my intention. Besides we would be supporting something what is not according to the specification. For me, a better solution for your problem is to write a preprocessor which would actually convert all integers into decimal (double) numbers.
