### ISSUE TITLE
Possible to color code terrain using this plugin? 

### ISSUE THREAD

**Issue by jesussmile** [jozes/flutter_map_geojson#5]
Is it possible to color code the terrain based on this plugin? For example is the terrain is at your current altitude then color code it red, if the terrain is below 500 feet then color code it yellow,  and if below thousand feet then color code it green ?

**Comment by jozes** [comment]
@jesussmile It is possible to use colours to display the terrain altitude. If I understand you correctly you would like to use different colours for the polygons regarding the height (altitude) of the area (polygon). If this is the case you should copy the the default polygon  creation function:

```
/// default callback function for creating [Polygon] - copied and renamed
  Polygon createMyPolygon(List<LatLng> outerRing,
      List<List<LatLng>>? holesList, Map<String, dynamic> properties) {
    return Polygon(
      points: outerRing,
      holePointsList: holesList,
      borderColor: defaultPolygonBorderColor!,
      color: defaultPolygonFillColor!,
      isFilled: defaultPolygonIsFilled!,
      borderStrokeWidth: defaultPolygonBorderStroke!,
    );
  }

// use the name of polygon creation function when instantiating the parser
  GeoJsonParser myGeoJson = GeoJsonParser(
        polygonCreationCallback: createMyPolygon)
  );
```

and rename it and as colour define the colour according to the altitude which is one of the properties, passed to this function. In the above example I just copied the function but you have to add the logic how to colour the polygons and ths you should define the non default colours for that.
Then use the name of this function when you instantiate the parser by defining polygonCreationCallback: <name of your function>. If polygonCreationCallback is defined and not null then the specified function is used for polygon creation otherwise the default polygon creation function is used. The same approach can be used for markers and polylines approach.
Hope that this answers your question.
